export const courseActionsTypes = {  
  CREATE_COURSE: 'CREATE_COURSE',
  CREATE_COURSE_SUCCESS : 'CREATE_COURSE_SUCCESS',
  SAVE_COURSE_SUCCESS : 'SAVE_COURSE_SUCCESS',
  LOAD_COURSES_SUCCESS : 'LOAD_COURSES_SUCCESS',
  DELETE_COURSE_OPTIMISTIC : 'DELETE_COURSE_OPTIMISTIC'
  
};

export const authorActionsTypes = { 
  CREATE_AUTHOR_SUCCESS : 'CREATE_AUTHOR_SUCCESS',
  LOAD_AUTHORS_SUCCESS : 'LOAD_AUTHORS_SUCCESS',
  UPDATE_AUTHOR_SUCCESS : 'UPDATE_AUTHOR_SUCCESS',
  DELETE_AUTHOR_OPTIMISTIC : 'DELETE_AUTHOR_OPTIMISTIC'
};

export const categoryActionsTypes = { 
  CREATE_CATEGORY_SUCCESS : 'CREATE_CATEGORY_SUCCESS',
  LOAD_CATEGORIES_SUCCESS : 'LOAD_CATEGORIES_SUCCESS',
  UPDATE_CATEGORY_SUCCESS : 'UPDATE_CATEGORY_SUCCESS',
  DELETE_CATEGORY_OPTIMISTIC : 'DELETE_CATEGORY_OPTIMISTIC'
};

export const BEGIN_API_CALL = 'BEGIN_API_CALL';
export const API_CALL_ERROR = 'API_CALL_ERROR';
