export const courseActionsTypes = {  
  CREATE_COURSE: 'CREATE_COURSE',
  CREATE_COURSE_SUCCESS : 'CREATE_COURSE_SUCCESS',
  SAVE_COURSE_SUCCESS : 'SAVE_COURSE_SUCCESS',
  LOAD_COURSES_SUCCESS : 'LOAD_COURSES_SUCCESS',
  DELETE_COURSE_OPTIMISTIC : 'DELETE_COURSE_OPTIMISTIC'
  
};
export const authorActionsTypes = { LOAD_AUTHORS_SUCCESS : 'LOAD_AUTHORS_SUCCESS'};
export const BEGIN_API_CALL = 'BEGIN_API_CALL';
export const API_CALL_ERROR = 'API_CALL_ERROR';
