export const courseActionsTypes = {  
  CREATE_COURSE: 'CREATE_COURSE',
  CREATE_COURSE_SUCCESS : 'CREATE_COURSE_SUCCESS',
  SAVE_COURSE_SUCCESS : 'SAVE_COURSE_SUCCESS',
  LOAD_COURSES_SUCCESS : 'LOAD_COURSES_SUCCESS'
};
export const authorActionsTypes = { LOAD_AUTHORS_SUCCESS : 'LOAD_AUTHORS_SUCCESS'};
export const BEGIN_API_CALL = 'BEGIN_API_CALL';